### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by PostboxRetinal** [PostboxRetinal/eCommerceIngSoftware#1]
# Expected Behavior
Send a POST request including a JSON object following this syntax and receive an HTTP 200:OK answer to log in successfully

``
{
    "identificacion":,
    "username":"",
    "password":"",
    "correo":""
}
``

# Current Behavior
WebApp returns an HTTP 200:OK code but npm console throws up:
``Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client``

# Failure Information (for bugs)
Please provide more information about the failure if this is a bug. If it is not a bug, you can remove this section.

## Steps to Reproduce
1. Start the dev instance with npm run dev
2.  Send a POST request to http://127.0.0.1:4000/api/auth/ with expected body
``
{
    "identificacion":,
    "username":"",
    "password":"",
    "correo":""
}
``
3. Observe HTTP 200:OK return on Postman client and ``Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`` on npm console

## Context
Please provide any relevant information about your setup, e.g., firmware version, operating system, SDK version, toolchain version. 

Node.js v21.6.2

## Screenshots

![20240401_002619](https://github.com/PostboxRetinal/eCommerceIngSoftware/assets/78338192/087e90b4-888a-4184-8263-abe05a8fd55c)

## Failure Logs
Please include any relevant log snippets or files.

```
node:_http_outgoing:703
    throw new ERR_HTTP_HEADERS_SENT('set');
          ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:703:11)
    at ServerResponse.header (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/node_modules/express/lib/response.js:795:10)
    at ServerResponse.send (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/node_modules/express/lib/response.js:175:12)
    at ServerResponse.json (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/node_modules/express/lib/response.js:279:15)
    at loginUsuario (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/controllers/auth.js:69:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by PostboxRetinal** [comment]
SOLVED with https://github.com/PostboxRetinal/eCommerceIngSoftware/commit/955e087d7239dde65ac0d98b8e3752aa2f5fccd3
