### ISSUE TITLE
Error: Route.get() requires a callback function but got a [object Promise]

### ISSUE THREAD

**Issue by PostboxRetinal** [PostboxRetinal/eCommerceIngSoftware#2]
**Describe the bug**
Implemented CORS and created tasks. Now ``npm run dev`` server isn't able to start properly

**To Reproduce**

1. Using the latest commit on branch ``tasks`` try to start the server with ``npm run dev``
2. See the bug

**Expected behavior**
Server should start following the new server.js file

**Screenshots**
![image](https://github.com/PostboxRetinal/eCommerceIngSoftware/assets/78338192/1bd6b9bf-6f11-4ba4-bad8-d12e87686524)

**Debug log**

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed Linux 6.8.1-1-default
 - Browser: Mozilla Firefox
 - Version: 124.0.1

**Additional context**

```
[nodemon] starting `node index.js`
Conectado a Base de Datos
/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/node_modules/express/lib/router/route.js:216
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Promise]
    at Route.<computed> [as get] (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/node_modules/express/lib/router/route.js:216:15)
    at proto.<computed> [as get] (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/routes/task.js:8:8)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Server.setRoutes (/home/bastian/Documents/UAO/ISO1/eCommerceIngSoftware/backend/server/server.js:38:39)

Node.js v21.6.2
```

**Comment by PostboxRetinal** [comment]
Solved with commit from on main branch https://github.com/eduardoacost/E-commerce-P.iNG.SOFTWARE/commit/85ad5f0bda194d971ee7f52f87d68f99c258f1f0
